### ISSUE TITLE
FE: Upgrade major dependencies

### ISSUE THREAD

**Issue by Haarolean** [kafbat/kafka-ui#111]

**Comment by germanosin** [comment]
@Mgrdich could you please provide details which major libs you will upgrade

**Comment by Mgrdich** [comment]
the main packages that needs an update

* `vite` -> version 5 ish
* `typescript` version 5 ish
* `floating-ui` version 0.26.10
* `@tanstack/react-query` -> version 5i sh
* `styled-componens` -> version 6ish
* `react` , `react-dom` -> 18.2.0
* `react-hook-form` -> 7.5.ish
* `zustand` -> 4.5.ish
* `react-router-dom`  -> 6.4
