### ISSUE TITLE
BE: RBAC: Ignore values for non-applicable resources

### ISSUE THREAD

**Issue by Sahay-ohikc** [kafbat/kafka-ui#253]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/SECURITY.md)

### Describe the bug (actual behavior)

I get the 500 errors while trying to get Broker configs or edit dynamic config of a cluster. 
Roman Zabaluev suggested that it may be a bug with RBAC. Logs and RBAC config are in the attachment.
[log-events-viewer-result.csv](https://github.com/kafbat/kafka-ui/files/14805841/log-events-viewer-result.csv)
[rbac-qa.zip](https://github.com/kafbat/kafka-ui/files/14805865/rbac-qa.zip)
<details>
<summary>Uploaded Files</summary>

![image](https://github.com/kafbat/kafka-ui/assets/71588899/3a72a0b9-4280-42b2-8b9f-942314fe508b)
![image](https://github.com/kafbat/kafka-ui/assets/71588899/9c624e3b-17b3-4026-b483-6a75cf6c2f61)
![image](https://github.com/kafbat/kafka-ui/assets/71588899/615a1288-75cb-4447-9ed0-22142ee9b922)
![image](https://github.com/kafbat/kafka-ui/assets/71588899/51a2482c-b43d-4ea5-9f71-39990745ca0c)

</details>

### Expected behavior

Cluster dynamic config reachable.
Broker configs tab working.

### Your installation details

I'm running an image [2956664](https://github.com/kafbat/kafka-ui/commit/2956664) v1.0.0 from ghcr.io/kafbat/kafka-ui:latest
I build a custom image in ECR with this simple Dockerfile:
FROM provectuslabs/kafka-ui:latest
COPY rbac-qa-test.yml /roles.yml
ENV  SPRING_CONFIG_ADDITIONAL-LOCATION /roles.yml
EXPOSE 8080
It is deployed on AWS ECS with AWS IAM authorization to Cluster and Cognito authorization to Kafka-UI with RBAC enabled.
Cluster config is transferred via env variables.
[rbac-qa.zip](https://github.com/kafbat/kafka-ui/files/14805865/rbac-qa.zip)

### Steps to reproduce

Use configuration to deploy KafkaUI, then click the appropriate "configure" button or broker config tab.

### Screenshots

<details>
<summary>Screenshots</summary>

![image](https://github.com/kafbat/kafka-ui/assets/71588899/3a72a0b9-4280-42b2-8b9f-942314fe508b)
![image](https://github.com/kafbat/kafka-ui/assets/71588899/9c624e3b-17b3-4026-b483-6a75cf6c2f61)
![image](https://github.com/kafbat/kafka-ui/assets/71588899/615a1288-75cb-4447-9ed0-22142ee9b922)
![image](https://github.com/kafbat/kafka-ui/assets/71588899/51a2482c-b43d-4ea5-9f71-39990745ca0c)

</details>

### Logs

1711720109267,java.lang.IllegalStateException: null
1711720109267,	at com.google.common.base.Preconditions.checkState(Preconditions.java:496)
1711720109267,	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 

1711720109267,Original Stack Trace:
1711720109267,		at com.google.common.base.Preconditions.checkState(Preconditions.java:496)
1711720109267,		at io.kafbat.ui.model.rbac.AccessContext$SingleResourceAccess.lambda$isAccessible$1(AccessContext.java:72)

 [log-events-viewer-result.csv](https://github.com/kafbat/kafka-ui/files/14805841/log-events-viewer-result.csv)

**Comment by Haarolean** [comment]
Fails at `io/kafbat/ui/model/rbac/AccessContext.java:72` due to the config containing non-allowed values for app and cluster configs:
```
        - resource: applicationconfig
#          value: ".*"
          actions: ALL
        - resource: clusterconfig
#          value: ".*"
          actions: ALL
```

TODO: 
1. Either ignore these or make it clear in logs (upon start, ideally) that the config is not valid.
