### ISSUE TITLE
Broker not shown when empty

### ISSUE THREAD

**Issue by IncandescentChrysalis** [kafbat/kafka-ui#254]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [ ] I've tried running `main`-labeled docker image and the issue still persists there
- [ ] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/SECURITY.md)

### Describe the bug (actual behavior)

In [`v0.6.2` from `provectus/kafka-ui`](https://github.com/provectus/kafka-ui/releases/tag/v0.6.2), when a cluster hosts some brokers containing data and other having none, the empty broker do not show up in the brokers list, despite being properly counted in the brokers count.

I have no idea is this might be related to #58, which I saw fixed in [`v1.0.0`](https://github.com/kafbat/kafka-ui/releases/tag/v1.0.0), or not.

### Your installation details

[`v0.6.2` from `provectus/kafka-ui`](https://github.com/provectus/kafka-ui/releases/tag/v0.6.2)

### Steps to reproduce

Ensure some brokers do not host any data (no replica from any partition), while some others do.
If there is no data at all, all brokers show up in the list.

**Comment by Haarolean** [comment]
Hi, versions below the latest major one are [not supported](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md).
Please do upgrade, feel free to ping me here if the issue persists.

**Comment by IncandescentChrysalis** [comment]
Upgrade to `v0.7.1` is not possible due to the long-standing #54 (historically provectus/kafka-ui#3741)

Is there any reason to believe it is fixed in that version? Based on which issues/PRs?

**Comment by Haarolean** [comment]
@IncandescentChrysalis #54 is not an issue, it's an enhancement, a new feature if you'd like. It wasn't present in any previous versions so I don't see how it can be a blocker for an upgrade.

Version 0.6 was released a year ago, I don't quite remember all of the changes made that could affect or fix the aforementioned issue.

**Comment by IncandescentChrysalis** [comment]
We couldn't manage to make authentication on our Active Directory backend work on `v0.7.1`.
The switch to RBAC not working (and documented so), we ended up sticking to that version.

**Comment by Haarolean** [comment]
@IncandescentChrysalis Authentication and RBAC are two distinct things, if there are any problems with LDAP/AD authentication, we'd need a separate issue for that. I'd look into that issue if you don't mind raising one.

This is the exact reason why older major versions are not supported as we can't always tell if some things have been fixed. I can reopen the issue if you manage to reproduce the same with 1.0.0. You can run a separate instance without authentication enabled to test things out.

Looking forward to seeing either an issue on AD authentication and/or results on verifying the issue with brokers within the latest release.

**Comment by IncandescentChrysalis** [comment]
I took some time to test `provectus/kafka-ui:v0.7.1` & `kafbat/kafka-ui:v1.0.0` and it seems the problem from this issue still arises with the former but not with the latter.
Looking good! Can't wait for production-readiness!

**Comment by Haarolean** [comment]
> I took some time to test `provectus/kafka-ui:v0.7.1` & `kafbat/kafka-ui:v1.0.0` and it seems the problem from this issue still arises with the former but not with the latter. Looking good! Can't wait for production-readiness!

that's great. That version is a stable release, you can use it :)

**Comment by IncandescentChrysalis** [comment]
I had some weird ARM/AMD architecture mismatch while testing based on your `v1.0.0` Docker Hub image.
It felt like the pipeline behind it was still WiP. ;)

There would still remain this AD thing to test, which was broken between `v0.6.2` & `v0.7.1`, before considering it.
