### ISSUE TITLE
BE: Security patches, April 2024 / CVE fixes

### ISSUE THREAD

**Issue by Haarolean** [kafbat/kafka-ui#256]
https://github.com/kafbat/kafka-ui/actions/runs/8491064444/job/23262694445

**Comment by Haarolean** [comment]
Fresh scan: https://github.com/kafbat/kafka-ui/actions/runs/11342129580/job/31541863418
up for grabs

**Comment by wernerdv** [comment]
@Haarolean can you re-run the scan?

If any CVEs are confirmed, I will prepare a PR.

**Comment by Haarolean** [comment]
@wernerdv sure, here's a fresh one:
https://github.com/kafbat/kafka-ui/actions/runs/12134889457/job/33832896961

**Comment by wernerdv** [comment]
@Haarolean I opened PR but did not update libcrypto3/libssl3 as it has low severity.
