### ISSUE TITLE
Access Smart Filters in r/o mode

### ISSUE THREAD

**Issue by vsimeonov-flutter** [kafbat/kafka-ui#272]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

When running Kafka UI in Read-Only mode you are not allowed to Add filters. 
The error returned is 
```
405 Method Not Allowed
This cluster is in read-only mode.
```

This issue is cause because filters are now registered in a separate request which is a POST one which is not allowed in r/o mode.

### Describe the feature you're interested in

I would like to Add filters in Read-Only mode.

### Describe alternatives you've considered

An alternative approach would be to turn off the Read-Only mode which bring security concerns related to the users of the service.
Another alternative is to turn on RBAC and provide proper set of Rules. This approach however is not preferable in during development on local machnine because Authentication method (different than Basic Auth) is required and this brings other issues to it.

### Version you're running

2956664 v1.0.0

### Additional context

This have been [raised as a question](https://discord.com/channels/897805035122077716/897805035122077719/1226133601540767845) in Discord and advised to be raised as issue here.

**Comment by Haarolean** [comment]
More of a regression as we introduced a separate enpoint for saving filters within #47. I guess saving filters (especially local for every user) is safe enough to bypass by r/o filter. Need to discuss how to approach this in a better way.
