### ISSUE TITLE
Can't create topic filter in "Read-only mode"

### ISSUE THREAD

**Issue by andreika63** [kafbat/kafka-ui#286]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

1) add cluster with Read-only mode checkbox selected
2) add topic filter like record.value.device.id == 137

Request URL: http://localhost:8081/api/clusters/prod/topics/resend-tasks/smartfilters
Request Method: POST
Status Code: 405 Method Not Allowed

request body:
`{"filterCode":"record.value.device.id == 137"}`

response body:
{"code":4003,"message":"This cluster is in read-only mode.","timestamp":1712837325324,"requestId":"3e10c336-125","fieldsErrors":null,"stackTrace":"io.kafbat.ui.exception.ReadOnlyModeException: This cluster is in read-only mode.
  at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
  Suppressed: The stacktrace has been enhanced by Reactor, refer to additional information below: 
Error has been observed at the following site(s):
  *__checkpoint ⇢ io.kafbat.ui.config.ReadOnlyModeFilter [DefaultWebFilterChain]
  *__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
  *__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
  *__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
  *__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
  *__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
  *__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
  *__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
  *__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
  *__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
  *__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
  *__checkpoint ⇢ HTTP POST \"/api/clusters/prod/topics/resend-tasks/smartfilters\" [ExceptionHandlingWebHandler]
Original Stack Trace:
    at reactor.core.publisher.MonoErrorSupplied.subscribe(MonoErrorSupplied.java:55)
 blah blah blah...
at java.base/java.lang.Thread.run(Thread.java:840)
"}

### Expected behavior

I can see filtered topic just in front of me 

### Your installation details

docker image
kafbat/kafka-ui:latest
7d264e4a5ec4

docker run --hostname=650185f7db03 --user=kafkaui --mac-address=xxxxxx --env=DYNAMIC_CONFIG_ENABLED=true --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --env=LANG=en_US.UTF-8 --env=LANGUAGE=en_US:en --env=LC_ALL=en_US.UTF-8 --env=TZ=Etc/UTC --env=JAVA_HOME=/usr/lib/jvm/zulu17 --env=JAVA_OPTS= -p 8081:8080 --restart=no --runtime=runc -d kafbat/kafka-ui:latest

[2956664](https://github.com/kafbat/kafka-ui/commit/2956664)
v1.0.0

### Steps to reproduce

1) add cluster with Read-only mode checkbox selected
2) add topic filter like record.value.device.id == 137

**Comment by andreika63** [comment]
Looks like it's already been fixed
https://github.com/kafbat/kafka-ui/pull/277

**Comment by andreika63** [comment]
Anyway, how to get a new docker image?

**Comment by Haarolean** [comment]
@andreika63 you could replace `image: ghcr.io/kafbat/kafka-ui:latest` with `image: ghcr.io/kafbat/kafka-ui:master`
