### ISSUE TITLE
BE: Messages: Stuck on polling partitions

### ISSUE THREAD

**Issue by Haarolean** [kafbat/kafka-ui#299]
via https://github.com/provectus/kafka-ui/issues/4434

**Comment by Haarolean** [comment]
@marcmesh FYI

We'll fix this within current release

**Comment by marcmesh** [comment]
🙏🏼 Thank you @Haarolean
As mentioned, the consumer seems to get into the same resuming -> assigned -> seeking to offset -> pausing -> resuming loop as in the logs from https://github.com/provectus/kafka-ui/issues/4434
