### ISSUE TITLE
Add ability to hide social links/icons on menu bar

### ISSUE THREAD

**Issue by dakotajd** [kafbat/kafka-ui#315]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md) and the feature is not present there

### Describe the feature you're interested in

I would like to propose the ability to hide the social links/icons (Discord, Patreon, GitHub) from the menu bar on the top right of the page.

This could be supported via environment variables or some other mechanism.

### Version you're running

2956664

**Comment by Haarolean** [comment]
Hi, this app is being developed in the spare time of our team members and we've put thousands of hours over the years into it. Considering the app is completely free, leaving a star on GitHub and a review on ProductHunt is the least one could do in return.
