### ISSUE TITLE
topic view  Newest filter and Oldest filter are upside-down

### ISSUE THREAD

**Issue by Eat-an-orange** [kafbat/kafka-ui#317]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

In topic view, choose Oldest button get the Newest messages,  and vice-versa
![JJ55SXGGmfmCjM2c2n8ZbhTes6CEewsK](https://github.com/kafbat/kafka-ui/assets/40664250/f908cc46-4ca2-4d68-b7c1-7421666e05e7)
![swyDnNmHFMZf8K2h2558wW8cMkQX56jh](https://github.com/kafbat/kafka-ui/assets/40664250/29454cfe-a9e8-4fe6-ba45-edd2cde977e9)

### Your installation details

kafbat/kafka-ui:v1.0.0
confluentinc/cp-kafka:6.2.1

### Steps to reproduce

go to any topic view, click messages button, then choose Newest filter

**Comment by Haarolean** [comment]
Hey, this has been fixed within #249. Feel free to pull `master` image :)
