### ISSUE TITLE
BE: Messages: Getting stuck on "polling partitions"

### ISSUE THREAD

**Issue by Haarolean** [kafbat/kafka-ui#319]
_via Discord:_

For topics with larger numbers of messages, clicking the "Next" button to load the next page of messages, or switching to Newest First sorting results in it getting stuck on "Polling Partitions". In the logs of the application, it shows the following 

```
INFO [boundedElastic-1719] o.a.k.c.u.AppInfoParser: App info kafka.consumer for kafka-ui-consumer-1712975021172 unregistered
INFO [boundedElastic-1719] c.p.k.u.e.EnhancedConsumer: [Consumer clientId=kafka-ui-consumer-1712975021172, groupId=null] Kafka consumer has been closed
```

Screen recording: 
https://discord.com/channels/897805035122077716/1228532718493761546/1232452982763687987

**Comment by iliax** [comment]
@Haarolean if recording still available?

**Comment by Haarolean** [comment]
@iliax updated the link

**Comment by iliax** [comment]
should be fixed with https://github.com/kafbat/kafka-ui/pull/406

**Comment by Haarolean** [comment]
duplicate of #299
