### ISSUE TITLE
FE: Unnecessary full page re-rendering

### ISSUE THREAD

**Issue by Haarolean** [kafbat/kafka-ui#320]
After a page refresh (cold loading) clicking on brokers triggers a full page re-render including the menu bar which has already been rendered
https://github.com/kafbat/kafka-ui/assets/1494347/c7f90540-854b-4fd3-9da9-9eb836f4fefb

**Comment by StefanG1102** [comment]
Hey Haarolean,

I am a student in Germany, and in one of my lectures, I need to work on an open-source project. I would like to look into this specific task.

**Comment by StefanG1102** [comment]
Thank you. I will give me best to solve this issue!

**Comment by StefanG1102** [comment]
If i create a Cluster and i click on Brokers i get an endless Loading screen until the whole website ist turning white. Did i do something wrong in the project Setup?

**Comment by Haarolean** [comment]
> If i create a Cluster and i click on Brokers i get an endless Loading screen until the whole website ist turning white. Did i do something wrong in the project Setup?

check your browser's console to see what's wrong

**Comment by StefanG1102** [comment]
i get a 500 Error with this message     "message": "Error while creating AdminClient for Cluster local",
<img width="811" alt="image" src="https://github.com/kafbat/kafka-ui/assets/166592974/74597b39-3cc9-417c-8105-d1c6ee4154bb">

**Comment by Haarolean** [comment]
@StefanG1102 this is a backend configuration issue. But I can't tell you what's wrong with just `Error while creating AdminClient for Cluster local` without looking at the backend (container) logs. If you're running one of the compose files (kafka-ui-arm64.yaml or kafka-ui.yaml) this should basically work out of the box. 
Please check our dev docs: https://ui.docs.kafbat.io/

You can run the command specified [here](https://ui.docs.kafbat.io/quick-start/demo-run) and set vite_dev_proxy in .env to localhost:8080.

I'm also available on discord if you need further help, the link is available in the project README.

**Comment by StefanG1102** [comment]
I apologize for my inability to resolve the issue despite my best efforts. It appears that the problem requires a level of expertise beyond my current skill set. Nonetheless, I sincerely appreciate the opportunity to try.

**Comment by Haarolean** [comment]
@StefanG1102 no worries! Please take a look at the "up for grabs" board, there are simpler issues for sure :)
https://github.com/orgs/kafbat/projects/2
