### ISSUE TITLE
FE: Create topic form is disabled with no obvious reason

### ISSUE THREAD

**Issue by Haarolean** [kafbat/kafka-ui#329]
A blank form opened without edits is disabled due to the number of partitions not selected, but there's no visible indication of which part of the form is invalid

TODO:
1. Fix the validation message for an empty "number of partitions" field
2. Set the number of partitions defaulted to 1 for this form

<img width="811" alt="image" src="https://github.com/kafbat/kafka-ui/assets/1494347/40ccdc1f-d62d-423a-a203-6591aa3108c8">

**Comment by LinusRichter** [comment]
Hello Haarolean, 
as far as I can see, the validation of the field "Number of Partitions" behaves in the same way as the validation of the other required field "Topic Name". Can you describe in more detail how "number of partitions" should behave?

**Comment by Haarolean** [comment]
> Hello Haarolean, as far as I can see, the validation of the field "Number of Partitions" behaves in the same way as the validation of the other required field "Topic Name". Can you describe in more detail how "number of partitions" should behave?

Let's just set the number of partitions to 1 upon opening this form.
