### ISSUE TITLE
UX: Allow Ctrl + F/Searching inside Schema Registry

### ISSUE THREAD

**Issue by camjmayhew** [kafbat/kafka-ui#345]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

Whenever I'm trying to search for a field in a schema, I'm unable to Ctrl + F, and thus have to paste the schema elsewhere to search.

### Describe the feature you're interested in

Allow a search bar/Ctrl + F inside the Schema Registry window.

### Version you're running

0.6

**Comment by Haarolean** [comment]
Hi, this seems to be an issue with the code editor within the schema registry page. As a workaround, you can click outside of the code block and use ctrl+f as usual.

**Comment by camjmayhew** [comment]
> Hi, this seems to be an issue with the code editor within the schema registry page. As a workaround, you can click outside of the code block and use ctrl+f as usual.

Yep but this only searches the text visible inside the code editor, e.g if the schema is longer than the code editor you can only search the small window at any time.

**Comment by camjmayhew** [comment]
This also happens in a topic when you try to search a record.

**Comment by yeikel** [comment]
This feature would be valuable during the Connector edit page of Kafka connect as well
