### ISSUE TITLE
FE: Do not refetch data on window focus

### ISSUE THREAD

**Issue by Haarolean** [kafbat/kafka-ui#348]
Some components like `ui/clusters/local/schemas/test/edit` does refetch data via tsquery on window focus.
This is considered a harmful behavior, because if there are any unsaved changes made to the schema itself the data will be refetched and the changes would be lost.

TODO:
1. Check all the places where window focus refetch is on but shouldn't be
2. Add `QUERY_REFETCH_OFF_OPTIONS` in these places

**Comment by masonwoodford** [comment]
Hey could I have this issue assigned to me please?

**Comment by masonwoodford** [comment]
Just to clarify, how were you thinking of determining if "window focus refresh is on but shouldn't be". Should it just be disabled on components that have editable portions?

**Comment by Haarolean** [comment]
> Just to clarify, how were you thinking of determining if "window focus refresh is on but shouldn't be". Should it just be disabled on components that have editable portions?

yeah sounds like a good approach. And we could always adjust this in the future.
