### ISSUE TITLE
Create ACL Button is enabled even if resource: acl is not listed in rbac config

### ISSUE THREAD

**Issue by Alexander-ac** [kafbat/kafka-ui#369]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

Dear team, we have created an RBAC list. One of the roles created should be **denied** access to the ACL. That works so far. However, the "+Create ACL" button in the top right corner is still active. And as a user I can even click on it and the Create ACL dialog is displayed. I think it's a bug and the button should be grayed out. Our RBAC configuration:

```typescript

rbac:
      roles:
        - name: "uat"
          clusters:
            - test
          subjects:
            - provider: oauth
              type: role
              value: "uat"
          permissions:
            - resource: applicationconfig
              actions: view
            - resource: clusterconfig
              actions: view
            - resource: topic
              value: "UAT_.*"
              actions: 
                - view
                - messages_read
            - resource: consumer
              value: "uat-.*"
              actions: view

``` 

with kind regards

Alex

### Expected behavior

I think it's a bug and the button should be grayed out.

### Your installation details

Version: 21.3.2024 (latest)

### Steps to reproduce

Create RBAC config

```typescript

rbac:
      roles:
        - name: "uat"
          clusters:
            - test
          subjects:
            - provider: oauth
              type: role
              value: "uat"
          permissions:
            - resource: applicationconfig
              actions: view
            - resource: clusterconfig
              actions: view
            - resource: topic
              value: "UAT_.*"
              actions: 
                - view
                - messages_read
            - resource: consumer
              value: "uat-.*"
              actions: view

``` 

Go to ACL Area.

### Screenshots

![image](https://github.com/kafbat/kafka-ui/assets/75088745/4c14f350-9ee1-495e-91fc-4edcaae005d1)

**Comment by Haarolean** [comment]
Fixed within #274
