### ISSUE TITLE
Display which schema id is used for deserializing a specific message

### ISSUE THREAD

**Issue by sappusaketh** [kafbat/kafka-ui#375]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

How does one know which schema/ schema id is used by kafka ui to deserialize a proto/avro any message which says key/value serde as `SchemaRegistry`?
<img width="314" alt="image" src="https://github.com/kafbat/kafka-ui/assets/43525626/a288eb2c-a04e-4587-9dda-51a181387f51">

### Describe the feature you're interested in

It would be nice to show schemaid or some clue next to schemaregistry saying which schema is used by kafka ui for serde

### Describe alternatives you've considered

We use confluent SR so all our producers serialize with confluent way of serializing i.e using magic bytes and including schema id with which message is serialized. I usually decode message to bytes and read schema Id if I have to debug something

### Version you're running

2956664

**Comment by Haarolean** [comment]
#77
