### ISSUE TITLE
Infra: Ship ARM images

### ISSUE THREAD

**Issue by hugomiguelabreu** [kafbat/kafka-ui#376]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

Whilst running the current `ghcr.io/kafbat/kafka-ui` image in a ARM based laptop with [podman](https://github.com/containers/podman), there is a unexpected error:
```
[Too many errors, abort]
```

This is due to having a ARM images built based of a sha256 explicit AMD image. Therefore, for the kafka-ui image, a base AMD image is being (zulu) used which is leading to this issue. 

### Expected behavior

Kafka UI container image runs out-of-the-box in both ARM and AMD architectures.

### Your installation details

```
docker run -it -p 8080:8080 ghcr.io/kafbat/kafka-ui
```

### Steps to reproduce

Have a ARM based laptop (e.g. M1) and install [podman](https://github.com/containers/podman) with docker integration.
After the setup, it is not possible to run the Kafka UI image due to AMD binaries in the base image.

### Logs

```
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts































[Too many errors, abort]
```

**Comment by Haarolean** [comment]
Hey, we're indeed planning to ship ARM images, but as a sidenote, our image works fine for me on apple silicon, but I use docker (orbstack to be precise) rather then podman.

**Comment by hugomiguelabreu** [comment]
Indeed! I also tested with Colima - https://github.com/abiosoft/colima - and it works as expected, though not with podman, after some investigation I assumed it is related with Rosetta support (podman rosetta support is still ongoing: https://github.com/containers/podman/pull/21670)

Nevertheless I have opened the PR - https://github.com/kafbat/kafka-ui/pull/378, this at least should ensure that the current shipped ARM image is based from a ARM Azul Java image
