### ISSUE TITLE
FE: Messages: Refresh doesn't refresh, it moves the offsets as if pagination

### ISSUE THREAD

**Issue by credmond** [kafbat/kafka-ui#416]
### Issue submitter TODO list

- [x] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

On the Topics -> Messages view with Newest, or Oldest selected, hitting "Refresh" appears to be doing pagination. If Newest is selected, and I hit Refresh, what is returned is not the newest, it's earlier offsets to what was currently displayed. It's not a refresh, all messages are lost from view and there's no way to go back.

If "Oldest" is selected, it's the same problem except in reverse; it keeps returning later and later messages.

### Expected behavior

Refresh refreshes the page (consuming latest messages if "Newest" selected or oldest if "Oldest") using offsets that correspond to the expectation of the user.

### Your installation details

[0f2ca72](https://github.com/kafbat/kafka-ui/commit/0f2ca72)

### Steps to reproduce

As per "Describe the bug" section. Just browse messages of any topic with a few thousand messages, and hit Refresh.

**Comment by Haarolean** [comment]
Thanks for submitting the bug, it is now fixed and available in `main`-tagged docker image

**Comment by credmond** [comment]
Unbelievable speed, thanks!
