### ISSUE TITLE
FE: Messages: Pagination has off-by-one error

### ISSUE THREAD

**Issue by Haarolean** [kafbat/kafka-ui#423]
<img width="317" alt="image" src="https://github.com/kafbat/kafka-ui/assets/1494347/d416d70c-72a3-47a4-8a59-7bdcfd7754f6">

<img width="260" alt="image" src="https://github.com/kafbat/kafka-ui/assets/1494347/2c92c257-b24e-4261-bac3-332bfec34a70">

**Comment by pithecuse527** [comment]
I would like to work on this. 
Could you please provide a more detailed explanation of how to reproduce the bug? I have not been able to identify any issues on pagination.

**Comment by Haarolean** [comment]
@pithecuse527 there should be 100 messages per page, however there are just 99

**Comment by Haarolean** [comment]
Turns out, there's an off-by-one error in my judgement, as the starting offset starts with 0 rather than 1, so there are, indeed, 100 records per page.
