### ISSUE TITLE
Message Count isn't always accurate

### ISSUE THREAD

**Issue by reidmeyer** [kafbat/kafka-ui#450]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

It's common to use highwater - lowwater to get message count, but this isn't always accurate.

If a topic is compacted or has transactional markers, the message count on the topics list isn't exactly accurate. 

related issue might be: https://github.com/provectus/kafka-ui/issues/3275

### Describe the feature you're interested in

A bit unclear. I'm not sure how to get message count without consuming the whole topic.. 

### Version you're running

42c236d

**Comment by Haarolean** [comment]
Hi, we're not aiming to display the precise message count for the reasons you've already mentioned -- that's not possible without reading out the topic completely. Can you elaborate on why do you need to see the precise message count for such topics?

**Comment by sappusaketh** [comment]
I had same case where I m comparing message count for source and target topics to ensure my Mirrormaker2 is replicating all data. Statistics page seem to show correct number where as summary is showing approx number

**Comment by Haarolean** [comment]
Indeed, using topic statistics is better suited for this goal.
