### ISSUE TITLE
 Kafka-UI is not showing the cluster info

### ISSUE THREAD

**Issue by rsurenderreddy** [kafbat/kafka-ui#459]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

I tried deploying kafka-UIon podman where I have provisioned the image. I have completed all the set up steps and while accessing the web page of kafka-UI it is not showing my cluster details.

i am able to get cluster details with MSK 2.8.1 on kafka ui but new msk version 3.5.1 is having issue.

i am using AWS MSK version of kafka 3.5.1 with IAM  SASL method.

### Expected behavior

it supposed to get cluster details on UI page

i checked /api/clsusters , it get empty reposnse back to UI

### Your installation details

APP: v1.0.0

### Steps to reproduce

test with msk 3.5.1 versiom

**Comment by Haarolean** [comment]
Please share the logs and the config

**Comment by rsurenderreddy** [comment]
attached logs and  config file

(https://gi[kafka.zip](https://github.com/user-attachments/files/16023904/kafka.zip)

**Comment by Haarolean** [comment]
@rsurenderreddy

```

$ unzip kafka.zip
Archive:  kafka.zip
warning [kafka.zip]:  zipfile is empty
```

**Comment by rsurenderreddy** [comment]
sorry my bad.. attached zip file

[kafka.zip](https://github.com/user-attachments/files/16053911/kafka.zip)

**Comment by Haarolean** [comment]
Please provide the outputs of:
`hostname/api/authorization`
`hostname/api/clusters`

**Comment by rsurenderreddy** [comment]
Here is the output of  api's

// https://kafkaui.xyz.com/api/clusters

[
  
]


// https://kafkaui.xyz.com/api/authorization

{
  "rbacEnabled": true,
  "userInfo": {
    "username": "sss@xyz.com",
    "permissions": [
      {
        "clusters": [
          "kafka-cluster"
        ],
        "resource": "APPLICATIONCONFIG",
        "value": null,
        "actions": [
          "VIEW",
          "EDIT"
        ]
      },
      {
        "clusters": [
          "kafka-cluster"
        ],
        "resource": "CLUSTERCONFIG",
        "value": null,
        "actions": [
          "VIEW",
          "EDIT"
        ]
      },
      {
        "clusters": [
          "kafka-cluster"
        ],
        "resource": "TOPIC",
        "value": ".*",
        "actions": [
          "VIEW",
          "CREATE",
          "EDIT",
          "DELETE",
          "MESSAGES_READ",
          "MESSAGES_PRODUCE",
          "MESSAGES_DELETE"
        ]
      },
      {
        "clusters": [
          "kafka-cluster"
        ],
        "resource": "CONSUMER",
        "value": ".*",
        "actions": [
          "VIEW",
          "DELETE",
          "RESET_OFFSETS"
        ]
      },
      {
        "clusters": [
          "kafka-cluster"
        ],
        "resource": "SCHEMA",
        "value": ".*",
        "actions": [
          "VIEW",
          "CREATE",
          "DELETE",
          "EDIT",
          "MODIFY_GLOBAL_COMPATIBILITY"
        ]
      },
      {
        "clusters": [
          "kafka-cluster"
        ],
        "resource": "CONNECT",
        "value": ".*",
        "actions": [
          "VIEW",
          "EDIT",
          "CREATE",
          "RESTART",
          "DELETE"
        ]
      },
      {
        "clusters": [
          "kafka-cluster"
        ],
        "resource": "KSQL",
        "value": null,
        "actions": [
          "EXECUTE"
        ]
      },
      {
        "clusters": [
          "kafka-cluster"
        ],
        "resource": "ACL",
        "value": ".*",
        "actions": [
          "VIEW"
        ]
      },
      {
        "clusters": [
          "kafka-cluster"
        ],
        "resource": "CLUSTERCONFIG",
        "value": null,
        "actions": [
          "VIEW"
        ]
      },
      {
        "clusters": [
          "kafka-cluster"
        ],
        "resource": "TOPIC",
        "value": ".*",
        "actions": [
          "VIEW",
          "MESSAGES_READ"
        ]
      },
      {
        "clusters": [
          "kafka-cluster"
        ],
        "resource": "CONSUMER",
        "value": ".*",
        "actions": [
          "VIEW"
        ]
      },
      {
        "clusters": [
          "kafka-cluster"
        ],
        "resource": "SCHEMA",
        "value": ".*",
        "actions": [
          "VIEW"
        ]
      },
      {
        "clusters": [
          "kafka-cluster"
        ],
        "resource": "CONNECT",
        "value": ".*",
        "actions": [
          "VIEW"
        ]
      }
    ]
  }
}

**Comment by hongbo-miao** [comment]
I am using MSK 3.7.x KRaft mode. Also, I am also having some issues.
I can confirm same IAM works well for Redpanda Console.

`https://horizon-kafbat-ui.example.com/api/authorization` returns

```json
{
"rbacEnabled": false,
"userInfo": null
}
```

`https://horizon-kafbat-ui.example.com/api/clusters` returns

```json
[
  {
    "name": "yaml",
    "defaultCluster": null,
    "status": "offline",
    "lastError": {
      "message": "Error while creating AdminClient for Cluster yaml",
      "stackTrace": "java.lang.IllegalStateException: Error while creating AdminClient for Cluster yaml\n\tat io.kafbat.ui.service.AdminClientServiceImpl.lambda$createAdminClient$5(AdminClientServiceImpl.java:56)\n\tat reactor.core.publisher.Mono.lambda$onErrorMap$28(Mono.java:3783)\n\tat reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)\n\tat reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)\n\tat reactor.core.publisher.FluxMap$MapConditionalSubscriber.onError(FluxMap.java:265)\n\tat reactor.core.publisher.Operators$MonoSubscriber.onError(Operators.java:1886)\n\tat reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:340)\n\tat reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onError(MonoCacheTime.java:363)\n\tat reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180)\n\tat reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:278)\n\tat reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:187)\n\tat reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)\n\tat reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)\n\tat java.base/java.lang.Thread.run(Thread.java:840)\nCaused by: org.apache.kafka.common.errors.SaslAuthenticationException: [4d37b931-0d78-44a1-bf2c-8ebbf55da91a]: Access denied\n"
    },
    "brokerCount": 0,
    "onlinePartitionCount": 0,
    "topicCount": 0,
    "bytesInPerSec": null,
    "bytesOutPerSec": null,
    "readOnly": false,
    "version": "Unknown",
    "features": []
  }
]
```

**Comment by rsurenderreddy** [comment]
i tested 3.5.1 with AKHQ UI, this is loading cluster

**Comment by hongbo-miao** [comment]
Hi @rsurenderreddy do you mean it didn't work when you open this ticket, and it works? Could you pos the solution? Thanks

**Comment by rsurenderreddy** [comment]
I opened this ticket for kafbat UI not for Akhq ui project.

I was testing AkHQ UI as a alternative solution for time being.

**Comment by hongbo-miao** [comment]
I see, sorry, my bad. Didn't read closely. Yeah both AKHQ and Redpanda Console works for us as well for MSK 3.7.x KRaft mode.
Hopefully Kafbat UI can support as well.

**Comment by Haarolean** [comment]
@hongbo-miao please raise a new issue, your case is a different issue

**Comment by hongbo-miao** [comment]
Thanks @Haarolean , I posted at https://github.com/kafbat/kafka-ui/discussions/483

**Comment by Haarolean** [comment]
@rsurenderreddy `/api/clusters` returning no clusters makes no sense tbh, considering it's present in the logs. Can you try disabling RBAC for testing purposes and checking again?

**Comment by rsurenderreddy** [comment]
issue with my rbac , it doesn't have cluster name tied with the role.

issue fixed now and thanks @Haarolean for the help
