### ISSUE TITLE
Consumers: Unsubscribe topics from consumer group

### ISSUE THREAD

**Issue by Boniker** [kafbat/kafka-ui#462]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

I noticed that the Kafka UI doesn’t have an opportunity to unsubscribe topics from consumer group.

Imagine a situation where you have a lag alert in your environment.
If you reset the offset, the situation will not change because the lag will remain and the topic will be subscribed to this customer group

### Describe the feature you're interested in

I request to be able to completely unsubscribe the topic from the customer group (like remove it from the cg)

AC: 
- stop consumer group
- unsubscribe topics button for all topics
- start consumer group

### Describe alternatives you've considered

we can do it via kafka server (better to do it via Kafka-ui):
```
kafka-consumer-groups --bootstrap-server <server>
   --delete-offsets -group <group_name> \
   --topic <topic_1> \
   --topic <topic_2> \
   --topic <topic_3>
```
### Version you're running

28677a90366791187787f1c7c0c26151648714e3

### Additional context

https://discord.com/channels/897805035122077716/1256173629306048522/1256173629306048522

**Comment by Boniker** [comment]
@Haarolean jfyi

**Comment by merzenniy** [comment]
+1

**Comment by fienlag** [comment]
+1

**Comment by Haarolean** [comment]
Since we have a PR submitted and approved and given the amount of interest in this issue, I'm moving this from 1.2 to an upcoming 1.1 release instead.
