### ISSUE TITLE
Cluster in Read Only mode - but why filter can not be saved

### ISSUE THREAD

**Issue by javapapo** [kafbat/kafka-ui#463]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

I run a single instance of kafka-ui on a production cluster in read only mode.

When I try to use the Filter functionality on a certain topic so I can search a topic  - I can not add a filter

![image](https://github.com/kafbat/kafka-ui/assets/484186/8ccd55fc-e11e-44e8-8c2a-2321bff0a2ec)

### Expected behavior

Why filters can not be added or work just because the cluster is on readonly mode?

### Your installation details

K8s single instance deployment, with basic auth, 1 pod.

### Steps to reproduce

Just configure readonly mode 

```    KAFKA_CLUSTERS_0_READ_ONLY: true```

### Screenshots

see above

### Additional context

No further contect

**Comment by Haarolean** [comment]
#272
