### ISSUE TITLE
Messages: Filters: Implement b64 decode

### ISSUE THREAD

**Issue by fallen-up** [kafbat/kafka-ui#464]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

in the old provectus version we could use groovy script:
```
String body = value.body.split(/\./)[1]
String unencoded = new String(Base64.decoder.decode(body), 'UTF-8')
unencoded.contains('aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee')
```

after removing groovy https://github.com/kafbat/kafka-ui/pull/98 try to do this:
`base64decode(record.key.body.split('.')[1]).contains('aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee')`

but we get an error:
```
400
CEL error. Original expression: base64decode(record.key.body.split('.')[1]).contains('aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee'). Error message: ERROR: <input>:1:13: undeclared reference to 'base64decode' (in container '') | base64decode(record.key.body.split('.')[1]).contains('aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee') | ............^ ERROR: <input>:1:35: undeclared reference to 'split' (in container '') | base64decode(record.key.body.split('.')[1]).contains('aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee') | ..................................^
```

### Your installation details

1.0

### Steps to reproduce

-

**Comment by Haarolean** [comment]
Added encoders and strings
https://github.com/google/cel-java/blob/main/extensions/src/main/java/dev/cel/extensions/README.md
