### ISSUE TITLE
Docker build for `linux/amd64` platform

### ISSUE THREAD

**Issue by sierikov** [kafbat/kafka-ui#471]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

Hey kafka-ui team,
I'm having trouble running the latest kafka-ui on my server with Portainer. The issue is that Portainer doesn't support the `platform` field in docker-compose, and probably won't anytime soon.

### Describe the feature you're interested in

Since I can't specify the `platform`, I can't use the latest `kafka-ui` image due to missing architecture on Docker Hub, but can use one from provectuslabs, where architecture is present. 

Any chance you could provide a workaround or publish the multi-arch image to the hub?

### Version you're running

1.0.0

**Comment by Haarolean** [comment]
Indeed, I see that docker hub contains only arm64 image. However, docker hub was used as a temporary mirror back then, and no images are being pushed there automatically at all. 
That is going to be changed within #237, we'll push all the images (release and snapshots) to docker hub and a public AWS ECR as well. That's gonna happen closer to the next release, I believe. Feel free to subscribe to that issue.

For now, I recommend pulling our ghcr repo: https://github.com/kafbat/kafka-ui/pkgs/container/kafka-ui
