### ISSUE TITLE
Upgrade to Java 21

### ISSUE THREAD

**Issue by yeikel** [kafbat/kafka-ui#490]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

No

### Describe the feature you're interested in

As Java 21 is the [latest LTS version](https://endoflife.date/oracle-jdk), I think that we should start testing(and releasing) the project using Java 21

### Describe alternatives you've considered

Using Multi-stage builds is an option but it puts me at risk of unknowns as the project is currently tested using Java 17. 

### Version you're running

2956664

### Additional context

We are currently using Java 17  

https://github.com/kafbat/kafka-ui/blob/8c7012679d7ec0293e0f96a1740690bf0bfc994e/pom.xml#L21

**Comment by Haarolean** [comment]
I don't mind, feel free to submit a PR.

**Comment by hugoabreu-fd** [comment]
@Haarolean, what would be the best approach here? A breaking change with a full upgrade to java 21 or two releases of jars / containers, one with 21 and another with 17?

**Comment by hugomiguelabreu** [comment]
@Haarolean, what would be the best approach here? A change with a full upgrade to java 21 or add maven profiles and CI stepa for two releases of jars / containers, one with 21 and another with 17?

**Comment by Haarolean** [comment]
@hugomiguelabreu the second option is too much overhead, so we're looking for a full upgrade :)
