### ISSUE TITLE
KC: Listing fails w/ connectors in STOPPED state

### ISSUE THREAD

**Issue by developster** [kafbat/kafka-ui#510]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

Kafka Connect tab is empty when at least one connector is in STOPPED state.

This state was added in Kafka 3.5.0. https://issues.apache.org/jira/browse/KAFKA-14783

### Your installation details

App version: 8c7012679d7ec0293e0f96a1740690bf0bfc994e

### Steps to reproduce

Stop one connector and open Kafka UI connectors tab.

**Comment by Haarolean** [comment]
Seems like a part of #183
