### ISSUE TITLE
BE: RBAC: Impl separate permissions for topic analysis

### ISSUE THREAD

**Issue by bachmanity1** [kafbat/kafka-ui#512]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md) and the feature is not present there

### Describe the feature you're interested in

Currently, any user authorized to view the topic can run the analysis. I believe this feature should be more restricted.

### Version you're running

8c7012679d7ec0293e0f96a1740690bf0bfc994e

**Comment by Haarolean** [comment]
>Currently, any user authorized to view the topic 
That's not true, only ones with `MESSAGES_READ` permission can run the analysis. There isn't a separate permission for this, because, basically if you have permission to read messages you can achieve the same result.
Please let me know if there are any other things we should consider.

**Comment by bachmanity1** [comment]
> That's not true, only ones with MESSAGES_READ permission can run the analysis.

Sorry, I meant to say read the topic, not view the topic. 

> if you have permission to read messages you can achieve the same result.

While this is true, I feel like access to this feature should be restricted because, for very large topics, reading all the data at once can put a heavy load on the cluster. To avoid unintentional consequences, I believe this action should be reserved only for privileged users. Besides that, looking at the code, it seems that ANALYSIS_RUN is not really used anywhere (please correct me if I'm wrong), and in my opinion, this case is an appropriate usage for it.

**Comment by Haarolean** [comment]
Sounds valid, let's proceed to your PR
