### ISSUE TITLE
ARM64 images on ghcr.io/kafbat/kafka-ui (multi arch) seems to be broken

### ISSUE THREAD

**Issue by espentj** [kafbat/kafka-ui#520]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

It seems the linux/arm64 image is actually an linux/amd64 image. When pulling the image from a pure ARM64 platform I end up with wrong format on startup of the container. 

### Expected behavior

A docker pull on a system incapable of running / emulating linux/amd64 will pull a non arm64 image from the ghcr.io/kafbat/kafka-ui container repo. Error message when starting container is:
 exec container process `/bin/sh`: Exec format error

### Your installation details

Kubernetes installation running on a HP ProLiant RL300 (Running Ampere Altra MAX arm CPUs).

### Steps to reproduce

On a system that cannot emulate linux/amd64 simply pull the latest docker image and run it.

**Comment by Haarolean** [comment]
Steps to reproduce?

```
$ uname -m
aarch64
$ docker pull ghcr.io/kafbat/kafka-ui:main
main: Pulling from kafbat/kafka-ui
a258b2a6b59a: Pull complete
2859bf77f9f5: Pull complete
5acbecbe06df: Pull complete
b4ea2b54f567: Pull complete
505ddaeda0b4: Pull complete
3e1e7553677f: Pull complete
d9bc3c582e89: Pull complete
Digest: sha256:21fdb77130855097a5611d6c30de6a554a21bc54d36dc5ec42b2e10dd24a658c
Status: Downloaded newer image for ghcr.io/kafbat/kafka-ui:main
ghcr.io/kafbat/kafka-ui:main

$ docker run ghcr.io/kafbat/kafka-ui:main
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
default THREAD FACTORY
 _   _ ___    __             _                _          _  __      __ _
| | | |_ _|  / _|___ _ _    /_\  _ __ __ _ __| |_  ___  | |/ /__ _ / _| |_____
| |_| || |  |  _/ _ | '_|  / _ \| '_ / _` / _| ' \/ -_) | ' </ _` |  _| / / _`|
 \___/|___| |_| \___|_|   /_/ \_| .__\__,_\__|_||_\___| |_|\_\__,_|_| |_\_\__,|
                                 |_|

2024-08-13 12:19:45,211 INFO  [main] i.k.u.KafkaUiApplication: Starting KafkaUiApplication using Java 17.0.11 with PID 1 (/api.jar started by kafkaui in /)
```

**Comment by Haarolean** [comment]
@espentj no worries. What was the "local error" if you're pulling the image?
