### ISSUE TITLE
v1.0.0 arm image doesn't work

### ISSUE THREAD

**Issue by VladislavMorozovIDT** [kafbat/kafka-ui#524]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [ ] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

v1.0.0 arm image doesn't work. main image works. We are using AWS arm linux ec2. AWS AMI id: ami-066399c5150a28574. AWS AMI name: amzn2-ami-ecs-hvm-2.0.20240818-arm64-ebs. 

### Expected behavior

v1.0.0 arm image works on arm aws ec2

### Your installation details

v1.0.0

### Steps to reproduce

1. start aws ec2 machine with AMI ami-066399c5150a28574
2. run docker run -it -p 8080:8080 -e DYNAMIC_CONFIG_ENABLED=true ghcr.io/kafbat/kafka-ui:v1.0.0

### Screenshots

![image](https://github.com/user-attachments/assets/92802e28-1895-4512-8914-83c2f9f43879)

### Logs

exec container process /bin/sh: Exec format error

**Comment by Haarolean** [comment]
This means this has been fixed later in main. You can either use `main`-tagged (or any other hash you're interested in if you require immutable tags) or wait for the 1.1.0 release

**Comment by VladislavMorozovIDT** [comment]
@Haarolean Could it be 1.0.1 fix?

**Comment by Haarolean** [comment]
@VladislavMorozovIDT we haven't planned one as it would require significant maintenance overhead.

**Comment by VladislavMorozovIDT** [comment]
@Haarolean When approximately will 1.1.0 be ready?

**Comment by kothapet** [comment]
Same issue here. I can only pull from docker hub, no main there.

**Comment by Haarolean** [comment]
@kothapet please raise a new issue
