### ISSUE TITLE
Messages of kafka show different result like for oldest shows the newest results and vice versa

### ISSUE THREAD

**Issue by Rubinagarg** [kafbat/kafka-ui#551]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

got to kafbat UI- topics-messages
Observe the oldest show the newest data results
And the latest show the oldest data results

### Expected behavior

the oldest should show the oldest data results
And the newest should show the newest data results

### Your installation details

[2956664](https://github.com/kafbat/kafka-ui/commit/2956664)
v1.0.0

### Steps to reproduce

https://kafka-ui.rc-athena.omr.oceaneering.com/ui/clusters/rc/all-topics/load-types/messages?limit=100&mode=LATEST
Check under messages , selected dropdown is oldest but result show up for newest/latest

### Logs

![image (36)](https://github.com/user-attachments/assets/dbad5731-6fc9-4787-a20d-ab3654c80593)

### Additional context

https://kafka-ui.rc-athena.omr.oceaneering.com/ui/clusters/rc/all-topics/load-types/messages?limit=100&mode=LATEST

**Comment by fallen-up** [comment]
https://github.com/kafbat/kafka-ui/issues/249
