### ISSUE TITLE
encrypted properties kafka-ui

### ISSUE THREAD

**Issue by kothapet** [kafbat/kafka-ui#568]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

I want to encrypt secrets that are passed to kafka-ui. I looked the code to see if they are using jasypt or spring-cloud encryption, but I don't see them in pom file. Do you support any encrypted properties in application properties/yaml file e.g. for clientId and secrets for sso.

### Describe the feature you're interested in

probably there are other options like using docker/k8 secrets if deployed as container. But trying to see if there is a way to do this natively from springboot.

### Describe alternatives you've considered

using docker/k8 secrets if deployed as container?? Any ideas.

### Version you're running

1.0.0

**Comment by Haarolean** [comment]
Hi, this is supported by our helm charts (see [this](https://github.com/kafbat/helm-charts/blob/main/charts/kafka-ui/values.yaml#L59)), we do not plan on implementing anything like this on app level, as this is mostly infra related. Let me know if you have any other questions.
