### ISSUE TITLE
UX: Messages: Use "Newest" as default mode

### ISSUE THREAD

**Issue by woile** [kafbat/kafka-ui#570]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

Most of the time, we have experienced that users want to see the newest first

### Describe the feature you're interested in

In here:

https://github.com/kafbat/kafka-ui/blob/3f3ca4cfabe36acd57fddcec1589c39a1800f61f/frontend/src/lib/hooks/useMessagesFilters.ts#L38

Use default 1, which would be `latest`

### Describe alternatives you've considered

Making it a configuration parameter, but I think "Newest" is good enough. I'd like to check here if everyone also agrees that Newest as default would be the best default. 

### Version you're running

1.0.0

**Comment by Haarolean** [comment]
I personally would prefer 'newest first' as well, let's see
