### ISSUE TITLE
BE: Null latest release information

### ISSUE THREAD

**Issue by vishal-bihani** [kafbat/kafka-ui#575]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

Applicaton information api is returning null latest release information.

<img width="1512" alt="Screenshot 2024-10-05 at 11 10 05 PM" src="https://github.com/user-attachments/assets/1e619d87-17d7-4084-b053-806ce3da3180">
 

### Expected behavior

Api should provide the latest release information.

### Your installation details

Commit Id: [2956664](https://github.com/kafbat/kafka-ui/commit/2956664)

### Steps to reproduce

Visit the homepage of Kafka-UI

**Comment by vishal-bihani** [comment]
We should recreate the Mono every single refresh.

**Comment by Haarolean** [comment]
Are there any logs on this matter? Most likely, it could be a request timeout

**Comment by vishal-bihani** [comment]
> Are there any logs on this matter? Most likely, it could be a request timeout

No, nothing spotted. 
[kafka-ui-logs.txt](https://github.com/user-attachments/files/17270141/kafka-ui-logs.txt)


Also default timeout is set to 10 seconds, it is very unlikely. Even if there is timeout, this approach doesn't seem reliable, have written an alternate, have a look: #577

**Comment by Haarolean** [comment]
@vishal-bihani could you please provide exact steps to reproduce the issue? Before we start looking into the PR, we need to understand what's the issue there.

This works fine for me on different commits (a bit older one and the latest from main) on different environments:
<img width="584" alt="image" src="https://github.com/user-attachments/assets/a06329b0-ed09-40d1-8a29-362f6cf37937">
<img width="603" alt="image" src="https://github.com/user-attachments/assets/e9b3ccc0-1780-4b16-bf1d-22a6122ba3c3">

**Comment by vishal-bihani** [comment]
Sure. Steps:
1. Pull the latest commit.
2. Build the docker image with new tag
3. Replace the current tag of kafka-ui in `documentation/compose/kafbat-ui.yaml` with the new one
4. Use docker compose to start the kafka cluster and the kafbat

# Image with the latest commit:
<img width="903" alt="Screenshot 2024-10-07 at 11 10 03 AM" src="https://github.com/user-attachments/assets/03232fd7-af43-477e-bdec-576c533334ac">


# Image with my commit:
<img width="903" alt="Screenshot 2024-10-07 at 11 00 03 AM" src="https://github.com/user-attachments/assets/09c0a271-806e-43e2-a1cd-95b3d4caa6e7">


As mentioned in previous commit, with TRACE level enabled, I don't see any timeout errors in the logs.

Device info:
OS: MacOS
Chip: M1

**Comment by Haarolean** [comment]
The second screenshot I provided has commit 941358d which is the most recent one from main. Not sure how to reproduce this.

**Comment by vishal-bihani** [comment]
Nothing changed from `8df11ac` to `941358d` in BE. But I was not able to reproduce in newer versions so closing this issue.
