### ISSUE TITLE
Success Message When Creating ACL but No ACL Items Found

### ISSUE THREAD

**Issue by kiranya-eevuri** [kafbat/kafka-ui#596]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

I encountered an issue while trying to create an ACL using the Kafka UI. After submitting the ACL creation form, I receive a success message indicating that the ACL has been created successfully. However, when I check the ACL list, it shows "No ACL items found."

I have refreshed the page and cleared the cache but the issue persists.

### Expected behavior

The newly created ACL should appear in the list of ACLs. It's similar to creating a group and assigning specific access rights to that group; the users within that group must have the corresponding access. This functionality is essential for effective access management.

### Your installation details

Application I have deployed in Openshift Redhat 
1.  App version - https://github.com/kafbat/kafka-ui/commit/2956664
2. helm chart - v3.9.3

### Steps to reproduce

1. Log in to Kafka UI:
Navigate to the Kafka UI login page.
Enter your credentials and log in.

2. Access the ACL Management:
From the main dashboard, select the "ACLs" option in the navigation menu.

3. Create a New ACL:
Click on the "Create ACL" button.
Fill in the required fields:
ACL Type: Select "Custom ACL".
Principal: Enter a valid principal (e.g., User:your_username).
Host Restriction: Enter the host.
Resource Type: Choose "TOPIC".
Operations: Select the desired operations (e.g., ALLOW, DENY, etc.).
Click "Submit" to create the ACL.

4. Check ACL List:
After the success message appears, refresh the ACL list.
Note that the list still shows "No ACL items found".

### Screenshots

![image](https://github.com/user-attachments/assets/ab46dd35-8cef-4b88-b523-667e38afefb9)
![image](https://github.com/user-attachments/assets/ace41639-42f0-40ff-8b01-a105cfd5a20a)

### Logs

I checked the logs, and it shows that the ACL was created:
DEBUG [parallel-1] i.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: kafka-dev
2024-10-09 13:20:28,269 DEBUG [parallel-1] i.k.u.s.ClustersStatisticsScheduler: Start getting metrics for kafkaCluster: kafka-dev
2024-10-09 13:20:28,678 DEBUG [parallel-1] i.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: kafka-dev
2024-10-09 13:20:55,666 INFO [reactor-http-epoll-4] i.k.u.s.a.AclsService: CREATING ACL: [user:kiranya.eevuri,TOPIC,PREFIXED,A,READ,ALLOW,*]
2024-10-09 13:20:55,670 INFO [parallel-1] i.k.u.s.a.AclsService: ACL CREATED: [user:kiranya.eevuri,TOPIC,PREFIXED,A,READ,ALLOW,*]
2024-10-09 13:20:58,269 DEBUG [parallel-1] i.k.u.s.ClustersStatisticsScheduler: Start getting metrics for kafkaCluster: kafka-dev
2024-10-09 13:20:58,523 DEBUG [parallel-1] i.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: kafka-dev
2024-10-09 13:21:28,269 DEBUG [parallel-1] i.k.u.s.ClustersStatisticsScheduler: Start getting metrics for kafkaCluster: kafka-dev

### Additional context

![image](https://github.com/user-attachments/assets/40e91d92-e81b-4092-9e55-39f59ceea1de)
If I use this env " - name: SPRING_CONFIG_ADDITIONALLOCATION
                               value: /roles.yml          "

And deploy in openshift, showing "No clusters Found" 
No info was there in UI page. 
==========
But when I remove that env and deploy, I am able see info and options..etc

**Comment by Haarolean** [comment]
Having 'Acl created' log message means we've done our part (the call via kafka client has succeeded).

- What kind of kafka and which version are you running?
- Have you tried reproducing this in other clusters?

We'd need a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for this, as this works in our environments. Feel free to use [this](https://github.com/kafbat/kafka-ui/blob/main/documentation/compose/ui-acl-with-zk.yaml) as a reference.

**Comment by kiranya-eevuri** [comment]
We are testing Kafka UI to implement a feature that creates read permissions for topics while restricting the ability to create or delete them, including the setup of groups and granting access accordingly. 

this is the files we using while deploying Kafka UI 
Value.yaml : 
[values-file.txt](https://github.com/user-attachments/files/17339481/values-file.txt)

ConfigMap file: 
[roles-file.txt](https://github.com/user-attachments/files/17339484/roles-file.txt)

**Comment by kiranya-eevuri** [comment]
Can you please help me, above issue.

**Comment by kiranya-eevuri** [comment]
Please look into above issue.

**Comment by kalavt** [comment]
We got same issue, here's exception logs:

```
2024-12-05 10:49:00,655 ERROR [reactor-http-epoll-6] o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler: [05588317-2916]  500 Server Error for HTTP GET "/api/clusters/msk-logs/acls"
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:496)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Handler io.kafbat.ui.controller.AclsController#listAcls(String, KafkaAclResourceTypeDTO, String, KafkaAclNamePatternTypeDTO, ServerWebExchange) [DispatcherHandler]
	*__checkpoint ⇢ io.kafbat.ui.config.CorsGlobalConfiguration$$Lambda$1034/0x00007f6e4065f7d0 [DefaultWebFilterChain]
	*__checkpoint ⇢ io.kafbat.ui.config.CustomWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ io.kafbat.ui.config.ReadOnlyModeFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ LogoutPageGeneratingWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ LoginPageGeneratingWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ OAuth2LoginAuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ OAuth2AuthorizationRequestRedirectWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/api/clusters/msk-logs/acls" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at com.google.common.base.Preconditions.checkState(Preconditions.java:496)
		at io.kafbat.ui.model.rbac.AccessContext$SingleResourceAccess.lambda$isAccessible$1(AccessContext.java:72)
		at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
		at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
		at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
```

**Comment by Haarolean** [comment]
@kalavt this is a different problem, please raise a new issue

**Comment by Haarolean** [comment]
@kiranya-eevuri as I mentioned earlier, we'd need a minimal reproducible example in the form of a docker compose with all the related containers (kafka brokers, in your case) to reproduce the issue. I've linked an example compose we usually use with standalone (confluent edition) kafka which works perfectly fine.
