### ISSUE TITLE
Add "Copy message" option

### ISSUE THREAD

**Issue by biergit** [kafbat/kafka-ui#600]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

I find myself copying header and values in order to resend a message

### Describe the feature you're interested in

I would like to have a simple "Copy message" option after which I headers, key, values etc. of the original message is copied which I can then adapt to my liking.

### Version you're running

https://github.com/kafbat/kafka-ui/commit/2956664

**Comment by biergit** [comment]
Ok, I just tried the "Keep contents" option and it is good enough for me. Thank you for this cool project btw.

**Comment by Haarolean** [comment]
Editing the message before reproducing it should be implemented within #318
