### ISSUE TITLE
Kafka Ui Ldap authentication login page takes around 1 minute to load

### ISSUE THREAD

**Issue by sankhyan** [kafbat/kafka-ui#602]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

Kafka Ui Ldap authentication login page takes around 1 minute to load

### Expected behavior

Kafka Ui Ldap authentication login page takes around 1 minute to load, it should be fast, logging is working fine

any property to use to reduce that time?

no error coming in logs, authentication also working fine but the login page is coming very late

### Your installation details

latest master image used
helm chart version is 0.7.6

### Steps to reproduce

ldap authentication properties

AUTH_TYPE: LDAP
SPRING_LDAP_URLS: ""
SPRING_LDAP_BASE: ""
SPRING_LDAP_ADMIN_USER: ""
SPRING_LDAP_USER_FILTER_SEARCH_BASE: ""
SPRING_LDAP_USER_FILTER_SEARCH_FILTER: ""
SPRING_LDAP_GROUP_FILTER_SEARCH_BASE: ""

**Comment by sankhyan** [comment]
@Haarolean 

hi, using below image

https://hub.docker.com/layers/kafbat/kafka-ui/latest/images/sha256-07492e3041cde8eb675c1604effbe2a3d374d00031589b7385a36d759015dc0e?context=explore

**Comment by Haarolean** [comment]
Can you take a look at browser's developer console, network tab, what's exactly loading that long?

**Comment by sankhyan** [comment]
i think below once getting timeout so may be its lating that much time, is that could be the case?

actually it's a private environment and internet is not accessible 

<img width="560" alt="image" src="https://github.com/user-attachments/assets/08459032-0384-40eb-9685-6a8d51469c1d">

**Comment by Haarolean** [comment]
>actually it's a private environment and internet is not accessible

should've started with that one :)

To be fixed within #72

**Comment by sankhyan** [comment]
@Haarolean 

thanks for the support, can you please let me this fix ETA?

**Comment by Haarolean** [comment]
@sankhyan as soon as I have spare time for that issue. That issue is the last important one for 1.1 release btw.

**Comment by vishaldhanani** [comment]
Hi, I'm facing the same issue using the latest tag **"main" & "v1.1.0"** images and it's not showing anything after login to the LDAP type "group". It's working fine with **"v1.0.0"** image but not sure what's causing on the latest images. Does anyone have documented how to resolve this issue? Looking forward to hearing to resolve it! Appreciate your help!

**Comment by Haarolean** [comment]
@vishaldhanani this sounds unrelated. Please raise a new issue/discussion and check your browser's dev console for issues
