### ISSUE TITLE
FE: Editing an existing filter doesn't have the CEL syntax help info available

### ISSUE THREAD

**Issue by Haarolean** [kafbat/kafka-ui#622]
When creating a filter there's quick info on CEL filters available when clicking on the question mark button:
<img width="565" alt="image" src="https://github.com/user-attachments/assets/c69e28bd-607f-4898-b141-11ccd766ecf9">
But one is missing when editing an existing filter:
<img width="571" alt="image" src="https://github.com/user-attachments/assets/13f98de1-5f9c-40d9-bbd0-79a05f8319a6">
TODO:
- add the same button for filter editing modal

**Comment by pisal-shubham** [comment]
Hello @Haarolean I will like to work on this issue. Can you please assign it to me ?
