### ISSUE TITLE
Ldap auth login page, missing css files 

### ISSUE THREAD

**Issue by polingsky** [kafbat/kafka-ui#641]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

I try to use ldap auth to login, but the login page try to access two css file from internet, 
https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css
https://getbootstrap.com/docs/4.0/examples/signin/signin.css

But my environment without internet, so the login page will missing css

Then, I modify login auth to basic auth, the login page will normal. It has not to access the two css files, 
so I want to ask the two scenarios are all normal??

### Your installation details

1. kafbat-ui-v1.0.0.jar

### Steps to reproduce

export AUTH_TYPE='LDAP'
export SPRING_LDAP_URLS='ldap://x.x.x.x:389'
export SPRING_LDAP_BASE='ou=users,ou=app,dc=org,dc=net'
export SPRING_LDAP_USER_FILTER_SEARCH_BASE='ou=users,ou=app,dc=org,dc=net'
export SPRING_LDAP_USER_FILTER_SEARCH_FILTER='(uid={0})'

### Screenshots

![kafka-ui-ldap-login](https://github.com/user-attachments/assets/e5165b5a-3c7a-43ea-a638-b0f77603e95a)

**Comment by Haarolean** [comment]
Basically the same as #622
External dependencies will be nuked within #72, please follow that issue
