### ISSUE TITLE
Message filter (smart filters based on Groovy syntax) no longer work

### ISSUE THREAD

**Issue by olivd4400** [kafbat/kafka-ui#664]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://ui.docs.kafbat.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I've tried running `main`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md)

### Describe the bug (actual behavior)

Adding a smart filter to messages page e.g. headers["my-header"] == "my-header-value" have no impact to displayed messages

### Expected behavior

Messages should be filtered according to smart filter (groovy syntax)

### Your installation details

7.2.0 

### Steps to reproduce

1. go to any topic with messages containing headers. 
2. add a new filter with a specific header value

### Additional context

used to work with version 7.1.0, no longer works with 7.2.0
we suspect a regression due to security fix of https://securitylab.github.com/advisories/GHSL-2023-229_GHSL-2023-230_kafka-ui/

**Comment by Haarolean** [comment]
Hi, thanks for reaching out.

- versions below 1.0.x are not supported.
- in kafbat we've replaced groovy with more approachable and secure CEL, once you upgrade you'll be able to see the quick info on CEL syntax
<img width="569" alt="image" src="https://github.com/user-attachments/assets/fa75fd0a-1768-49fa-8ce7-d9023d238a4d">

Let me know if you have any other questions.
