### ISSUE TITLE
FE: Is available to support property format in Kafka Connect?

### ISSUE THREAD

**Issue by jx2lee** [kafbat/kafka-ui#699]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

I used to lenses-io connect-ui, this supported property format. but, I'm using kafka-ui, Not providing a property format was inconvenient.

### Describe the feature you're interested in

I need to support property formatted in ui to convert json!

### Describe alternatives you've considered

![image](https://github.com/user-attachments/assets/de61c30c-6086-4b54-ab85-2d7cf70371d9)

I wish there was above img, to select what i want to used. (maybe properties & json)

### Version you're running

2956664

**Comment by yeikel** [comment]
The Kafka Connect REST Interface [only allows JSON messages](https://docs.confluent.io/platform/current/connect/references/restapi.html#content-types). Could you clarify where can you post property files?

**Comment by jx2lee** [comment]
@yeikel Oh, I wrote the issue wrong.

> Or is your request that the UI converts the property files to a JSON and publishes that?

I need the UI to convert the property files to JSON. I checked and the connect REST interface only accepts JSON, I'll fix issue body!

--> TLDR; feature to convert property files a JSON

**Comment by Haarolean** [comment]
Why? Who uses .properties if only json is supported?

**Comment by yeikel** [comment]
think that it is probably easier to use any of the online converters than to delegate this responsibility to the UI

**Comment by Haarolean** [comment]
While JSON is a native format for KC configs, I doubt supporting a custom format like properties will bring any good value, and given our limited bandwidth for this, I doubt this will ever be implemented. However, if you're willing to submit a PR for this, we can take a look. For the time being, I'll close this issue. Thanks for your suggestions!
