### ISSUE TITLE
Publish dependency analysis

### ISSUE THREAD

**Issue by yeikel** [kafbat/kafka-ui#706]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/kafbat/kafka-ui/issues)
- [X] I'm running a supported version of the application which is listed [here](https://github.com/kafbat/kafka-ui/blob/main/.github/SECURITY.md) and the feature is not present there

### Is your proposal related to a problem?

Yes, we can get dependabot alerts for all the dependencies including transitive dependencies

### Describe the feature you're interested in

Onboard the project to the [maven dependency tree dependency submission action ](https://github.com/marketplace/actions/maven-dependency-tree-dependency-submission) to generate generate a complete dependency graph for the project and submit the graph to the GitHub repository so that the graph is complete and includes all the transitive dependencies.

### Version you're running

318bcc91ddcca72b6a280d20f5f51ea85dac77c0

### Additional context

https://github.com/marketplace/actions/maven-dependency-tree-dependency-submission

**Comment by yeikel** [comment]
As per the latest update, setting up the action manually shouldn't be needing 

I am leaving the issue open to action enabling automatic submission from the repository settings. Feel free to close afterwards 

Cc @Haarolean

**Comment by Haarolean** [comment]
> enabling automatic submission from the repository settings.

it's been done the same day, thanks
