### ISSUE TITLE
Wizard: No enum constant com.provectus.kafka.ui.model.ActionDTO.view

### ISSUE THREAD

**Issue by Haarolean** [kafbat/kafka-ui#80]
via https://github.com/provectus/kafka-ui/issues/4308

```
java.lang.IllegalArgumentException: No enum constant com.provectus.kafka.ui.model.ActionDTO.view
        at java.base/java.lang.Enum.valueOf(Enum.java:273)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyExceptio**
```

TODO: Come up with a way to treat these enums with ignoring the case (view = VIEW)

Impl details:

A config like this:
```
        - resource: clusterconfig
          value: ".*"
          actions: all
```

when accessed via wizard and mapped via `PropertiesMapper` in `ApplicationConfigController` fails with the aforementioned exception as it tried to map 1:1 without ignoring the case. 

Also, it tried to map the "all" action as well which doesn't exist in the enum.

**Comment by iliax** [comment]
fix: https://github.com/kafbat/kafka-ui/pull/278
