### ISSUE TITLE
FE: Rename "max size on disk" to "Max partition size"

### ISSUE THREAD

**Issue by Haarolean** [kafbat/kafka-ui#86]
https://github.com/provectus/kafka-ui/issues/4037

TODO:
- Rename "max size on disk" to "Max partition size"

<img width="417" alt="image" src="https://github.com/kafbat/kafka-ui/assets/1494347/8e71775e-593a-4a0b-8386-881f8e919fcc">

**Comment by Haarolean** [comment]
Description updated, good for grabs 👀

**Comment by svrmnk** [comment]
I'd like to work on this!
